/**
 * {@link https://cspell.org/configuration/document-settings/} Documentation
 * @type {import('@cspell/cspell-types').Settings}
 */
module.exports = {
    version: '0.2',
    language: 'en,fr',
    import: ['@cspell/dict-fr-fr/cspell-ext.json'],
    ignorePaths: [
        'settings.json',
        '*.d.ts',
        '*.svg',
        '*.env',
        '*.gitignore',
        '**/.husky/**',
        '**/.devcontainer/**',
        '.github/**',
        '.git/**',
        'public/documents/**',
        'public/llms.txt',
    ],
    ignoreWords: [
        // About libraries
        'wdyr',
        'stylelint',
        'bulma',
        'djwt',
        'symfony',
        'gitmojis',
        'airbnb',
        'lintstagedrc',
        'stylelintrc',
        'knip',
        'stylelintcache',
        'turbopack',
        'llms',
    ],
    words: [
        // Specific to the project
        'kirian',
        'caumes',
        'linkedin',
        'github',
        'kiriancaumes',
        'kellermann',
        'télécom',
        'batinić',
        'pexels',
        'belochkin',
        'batinić',
        'legales',
        'ynov',
        'rncp',
        'ingésup',
        'belpois',
        'lyoko',
        'thouaré',
        'ajesterscollection',
        'gdpr',
        'balsamiq',
        'smacss',
        'firefox',
        'youtu',
        'instagram',
        'thenounproject',
        'aomam',
        'sympy',
        'llamaindex',
        'scalables',
        // Common
        'devcontainer',
        'esnext',
        'runtine',
        'fullhd',
        'fullwidth',
        'webp',
        'lqip',
        'camelcase',
        'changefreq',
        'postbuild',
        'pageview',
        'adduser',
    ],
}
