version: '3'
services:
  kiriancaumes_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app_kiriancaumes:rw

      - ~/.ssh:/.ssh
    ports:
      - "5000:5000"
      - '3000:3000'
    networks:
      - kiriancaumes_network

networks:
  kiriancaumes_network:
    driver: "bridge"
